/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Dynamic theme colors — resolved via CSS variables injected by useThemeStore
        "background":            "var(--background)",
        "on-background":         "var(--on-background)",
        "on-surface":            "var(--on-surface, var(--on-background))",
        "primary":               "var(--primary)",
        "primary-container":     "var(--primary)",
        "primary-fixed":         "var(--primary)",
        "primary-fixed-dim":     "var(--primary)",
        "error":                 "var(--primary)",
        "surface-tint":          "var(--primary)",
        "monolith-red":          "var(--primary)",
        "surface":               "var(--surface)",
        "surface-dim":           "var(--surface)",
        "surface-variant":       "var(--surface-container)",
        "surface-container":     "var(--surface-container)",
        "surface-container-low": "var(--surface-container-low)",
        "surface-container-high":"var(--surface-container-high)",
        "surface-container-highest": "var(--surface-container-high)",
        "surface-bright":        "var(--surface-container-high)",
        "outline":               "var(--outline, #696868)",
        "inverse-surface":       "var(--on-background)",
        "inverse-primary":       "var(--primary)",
        // Static colors
        "secondary":                    "#c8c6c5",
        "tertiary":                     "#c8c6c5",
        "tertiary-container":           "#696868",
        "tertiary-fixed":               "#e5e2e1",
        "tertiary-fixed-dim":           "#c8c6c5",
        "secondary-fixed":              "#e5e2e1",
        "secondary-fixed-dim":          "#c8c6c5",
        "secondary-container":          "#4a4949",
        "on-primary":                   "#ffffff",
        "on-primary-container":         "#ffffff",
        "on-primary-fixed":             "#410005",
        "on-primary-fixed-variant":     "#930017",
        "on-secondary":                 "#313030",
        "on-secondary-fixed":           "#1c1b1b",
        "on-secondary-fixed-variant":   "#474646",
        "on-secondary-container":       "#bab8b7",
        "on-tertiary":                  "#313030",
        "on-tertiary-fixed":            "#1c1b1b",
        "on-tertiary-fixed-variant":    "#474746",
        "on-tertiary-container":        "#ebe8e7",
        "on-error":                     "#690005",
        "on-error-container":           "#ffffff",
        "on-surface-variant":           "var(--on-background)",
        "inverse-on-surface":           "#2f3131",
        "error-container":              "#93000a",
        "surface-container-lowest":     "#0d0e0f",
      },
      fontFamily: {
        manrope: ['Manrope', 'sans-serif'],
      },
      spacing: {
        "unit": "8px",
        "stack-md": "32px",
        "stack-lg": "48px",
        "stack-sm": "16px",
        "section-gap": "128px",
        "margin-desktop": "80px",
        "container-max": "1440px",
        "gutter": "32px"
      },
      fontSize: {
        "label-caps": ["12px", {"lineHeight": "1.0", "letterSpacing": "0.15em", "fontWeight": "700"}],
        "caption": ["13px", {"lineHeight": "1.4", "letterSpacing": "0.01em", "fontWeight": "500"}],
        "display-lg": ["56px", {"lineHeight": "1.1", "letterSpacing": "-0.03em", "fontWeight": "700"}],
        "display-xl": ["72px", {"lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "800"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "letterSpacing": "0em", "fontWeight": "400"}],
        "headline-xl": ["40px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "1.6", "letterSpacing": "0em", "fontWeight": "400"}]
      },
      borderRadius: {
        'none': '0',
        'sm': '0',
        'DEFAULT': '0',
        'md': '0',
        'lg': '0',
        'xl': '0',
        '2xl': '0',
        '3xl': '0',
        'full': '9999px', // Keep full for potential circles, but user said cards/everything sharp. I'll set all to 0 except full maybe? User said "zero border radius on every card". I'll set all to 0.
      },
      letterSpacing: {
        tighter: '-0.04em',
        tight: '-0.02em',
        widest: '0.3em',
      },
    },
  },
  plugins: [],
}
